- name: Configure visualization stack
  hosts: all
  become: true

  vars:
    influx_download_url: https://dl.influxdata.com/influxdb/releases/influxdb-1.7.6.x86_64.rpm
    grafana_download_url: https://dl.grafana.com/oss/release/grafana-6.1.6-1.x86_64.rpm

  tasks:
  - name: Create certs
    shell: |
      HOSTNAME=`hostname`
      openssl req -newkey rsa:4096 -nodes -keyout /etc/grafana/grafana_key.pem -x509 -out /etc/grafana/grafana_cert.pem  -subj "/CN=${HOSTNAME}" 
      openssl req -newkey rsa:4096 -nodes -keyout /etc/influxdb/influx_key.pem -x509 -out /etc/influxdb/influx_cert.pem  -subj "/CN=${HOSTNAME}" 

  - name: Install InfluxDB
    yum: 
      name: "{{ influx_download_url }}"
      state: present

  - name: Copy Influx config
    copy:
      src: ./influxdb.conf
      dest: /etc/influxdb/influxdb.conf

  - name: Start InfluxDB
    systemd:
      name: influxdb
      state: restarted
      enabled: true
      masked: false

  - name: Create InfluxDB database
    shell: influx -ssl -unsafeSsl -execute 'create database telemetry'

  - name: Install Grafana
    yum:
      name: "{{ grafana_download_url }}"
      state: present

  - name: Copy Grafana config
    copy:
      src: ./grafana.ini
      dest: /etc/grafana/grafana.ini

  - name: Allow Grafana to bind to privileged ports
    shell: setcap 'cap_net_bind_service=+ep' /usr/sbin/grafana-server

  - name: Start Grafana
    systemd:
      name: grafana-server
      state: restarted
      enabled: true
      masked: false

  - name: Enable HTTPS service
    firewalld:
      service: https
      permanent: yes
      state: enabled
      zone: public
      immediate: yes
